/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.nsxDAO;
import DTO.nha_san_xuat;
import java.util.ArrayList;
import java.util.Vector;
import javax.management.StringValueExp;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gjang
 */
public class themnsx extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    
     
     
     ArrayList<nha_san_xuat> listnhasanxuat = new ArrayList<nha_san_xuat>();
    public themnsx() {
        initComponents();
        showlist();
        
    } 
    
    public void showlist(){
    
       nsxDAO nsxdao = new nsxDAO();
//     Vector<nha_san_xuat> listnsx = nsxdao.allnsx();
//        jListnsx.setListData(listnsx);
       listnhasanxuat= nsxdao.allnsx();
       DefaultTableModel tblnsx = (DefaultTableModel)jtblnsx.getModel();
       tblnsx.setRowCount(0);
       for(nha_san_xuat nsx : listnhasanxuat){
           int id = nsx.getId();
           String name = nsx.getName();
           String email = nsx.getEmail();
           String address = nsx.getAddress();
           String phone = nsx.getPhone();
           tblnsx.addRow(new Object[]{id,name,address,email,phone});
       }
       
    }
    public void returnNULL(String rong){
        rong = "";
        jname.setText(rong);
        jemail.setText(rong);
        jphone.setText(rong);
        jaddress.setText(rong);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jname = new javax.swing.JTextField();
        jaddress = new javax.swing.JTextField();
        jphone = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jupdate = new javax.swing.JButton();
        jidnsx = new javax.swing.JTextField();
        jdelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblnsx = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jemail = new javax.swing.JTextField();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 153, 51));
        jLabel1.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        jLabel1.setText("Name");

        jLabel2.setBackground(new java.awt.Color(255, 153, 51));
        jLabel2.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        jLabel2.setText("Address");

        jLabel3.setBackground(new java.awt.Color(255, 153, 51));
        jLabel3.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        jLabel3.setText("Phone");

        jname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnameActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 204));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 204, 51));
        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("List Nha San Xuat");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jupdate.setBackground(new java.awt.Color(255, 204, 204));
        jupdate.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jupdate.setForeground(new java.awt.Color(0, 153, 204));
        jupdate.setText("Update");
        jupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jupdateActionPerformed(evt);
            }
        });

        jidnsx.setEditable(false);
        jidnsx.setBackground(new java.awt.Color(255, 204, 0));
        jidnsx.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jidnsx.setForeground(new java.awt.Color(0, 0, 204));
        jidnsx.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jidnsx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jidnsxActionPerformed(evt);
            }
        });

        jdelete.setBackground(new java.awt.Color(255, 204, 204));
        jdelete.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jdelete.setForeground(new java.awt.Color(0, 153, 204));
        jdelete.setText("Delete");
        jdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdeleteActionPerformed(evt);
            }
        });

        jtblnsx.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtblnsx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "ADDRESS", "EMAIL", "PHONE"
            }
        ));
        jtblnsx.setColumnSelectionAllowed(true);
        jtblnsx.setUpdateSelectionOnSort(false);
        jtblnsx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblnsxMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblnsx);

        jLabel5.setBackground(new java.awt.Color(255, 153, 51));
        jLabel5.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        jLabel5.setText("Email");

        jemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jemailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jphone)
                            .addComponent(jaddress)
                            .addComponent(jname, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(jemail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jupdate)
                        .addGap(12, 12, 12)
                        .addComponent(jdelete)
                        .addGap(51, 51, 51)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jidnsx, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jidnsx, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jupdate)
                            .addComponent(jdelete)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        nha_san_xuat nsx = new nha_san_xuat();
        nsx.setName(jname.getText());
        nsx.setAddress(jaddress.getText());
        nsx.setPhone(jphone.getText());
        nsx.setEmail(jemail.getText());
        
        nsxDAO nsxdao = new nsxDAO();
      
        if(nsxdao.luusp(nsx)>0){
            JOptionPane.showMessageDialog(rootPane, "thanh cong");
         showlist();
            
        }
        else JOptionPane.showMessageDialog(rootPane, "that bai");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jupdateActionPerformed
        nha_san_xuat nsx = new nha_san_xuat();
        nsx.setName(jname.getText());
        nsx.setAddress(jaddress.getText());
        nsx.setPhone(jphone.getText());
        nsx.setEmail(jemail.getText());
        nsx.setId(Integer.parseInt(jtblnsx.getValueAt(jtblnsx.getSelectedRow(), 0).toString()));
        nsxDAO nsxdao = new nsxDAO();
      
        if(nsxdao.update(nsx)>0){
            JOptionPane.showMessageDialog(rootPane, "thanh cong");
            
            returnNULL("");
            showlist();
        }
        else JOptionPane.showMessageDialog(rootPane, "that bai");
        
    }//GEN-LAST:event_jupdateActionPerformed

    private void jidnsxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jidnsxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jidnsxActionPerformed

    private void jnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnameActionPerformed

    private void jdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdeleteActionPerformed
        // TODO add your handling code here:
        nha_san_xuat nsx = new nha_san_xuat();
        nsx.setId(Integer.parseInt(jtblnsx.getValueAt(jtblnsx.getSelectedRow(), 0).toString()));
        nsxDAO nsxdao = new nsxDAO();
      
        if(nsxdao.delete(nsx)>0){
            JOptionPane.showMessageDialog(rootPane, "thanh cong");
            showlist();
            returnNULL("");
            
        }
        else JOptionPane.showMessageDialog(rootPane, "that bai");
    }//GEN-LAST:event_jdeleteActionPerformed

    private void jemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jemailActionPerformed

    private void jtblnsxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblnsxMouseClicked
        // TODO add your handling code here:
        nsxDAO nsxdao = new nsxDAO();
        listnhasanxuat.clear();
        listnhasanxuat = nsxdao.allnsxbyId(jtblnsx.getValueAt(jtblnsx.getSelectedRow(), 0).toString());
        for(nha_san_xuat nsx : listnhasanxuat){
            jname.setText(nsx.getName());
            jaddress.setText(nsx.getAddress());
            jemail.setText(nsx.getEmail());
            jphone.setText(nsx.getPhone());
        }
    }//GEN-LAST:event_jtblnsxMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(themnsx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(themnsx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(themnsx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(themnsx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new themnsx().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jaddress;
    private javax.swing.JButton jdelete;
    private javax.swing.JTextField jemail;
    private javax.swing.JTextField jidnsx;
    private javax.swing.JTextField jname;
    private javax.swing.JTextField jphone;
    private javax.swing.JTable jtblnsx;
    private javax.swing.JButton jupdate;
    // End of variables declaration//GEN-END:variables
}
